//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.04 at 01:57:49 PM BRT 
//


package reinf;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the reinf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Signature_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Signature");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: reinf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Reinf }
     * 
     */
    public Reinf createReinf() {
        return new Reinf();
    }

    /**
     * Create an instance of {@link SignedInfoType }
     * 
     */
    public SignedInfoType createSignedInfoType() {
        return new SignedInfoType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link Reinf.EvtTotalContrib }
     * 
     */
    public Reinf.EvtTotalContrib createReinfEvtTotalContrib() {
        return new Reinf.EvtTotalContrib();
    }

    /**
     * Create an instance of {@link Reinf.EvtTotalContrib.InfoTotalContrib }
     * 
     */
    public Reinf.EvtTotalContrib.InfoTotalContrib createReinfEvtTotalContribInfoTotalContrib() {
        return new Reinf.EvtTotalContrib.InfoTotalContrib();
    }

    /**
     * Create an instance of {@link Reinf.EvtTotalContrib.InfoTotalContrib.RTom }
     * 
     */
    public Reinf.EvtTotalContrib.InfoTotalContrib.RTom createReinfEvtTotalContribInfoTotalContribRTom() {
        return new Reinf.EvtTotalContrib.InfoTotalContrib.RTom();
    }

    /**
     * Create an instance of {@link SignatureType }
     * 
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link TStatus }
     * 
     */
    public TStatus createTStatus() {
        return new TStatus();
    }

    /**
     * Create an instance of {@link TRegistroOcorrencias }
     * 
     */
    public TRegistroOcorrencias createTRegistroOcorrencias() {
        return new TRegistroOcorrencias();
    }

    /**
     * Create an instance of {@link TDadosProcessamentoEvento }
     * 
     */
    public TDadosProcessamentoEvento createTDadosProcessamentoEvento() {
        return new TDadosProcessamentoEvento();
    }

    /**
     * Create an instance of {@link KeyInfoType }
     * 
     */
    public KeyInfoType createKeyInfoType() {
        return new KeyInfoType();
    }

    /**
     * Create an instance of {@link SignatureValueType }
     * 
     */
    public SignatureValueType createSignatureValueType() {
        return new SignatureValueType();
    }

    /**
     * Create an instance of {@link TransformType }
     * 
     */
    public TransformType createTransformType() {
        return new TransformType();
    }

    /**
     * Create an instance of {@link TransformsType }
     * 
     */
    public TransformsType createTransformsType() {
        return new TransformsType();
    }

    /**
     * Create an instance of {@link X509DataType }
     * 
     */
    public X509DataType createX509DataType() {
        return new X509DataType();
    }

    /**
     * Create an instance of {@link SignedInfoType.CanonicalizationMethod }
     * 
     */
    public SignedInfoType.CanonicalizationMethod createSignedInfoTypeCanonicalizationMethod() {
        return new SignedInfoType.CanonicalizationMethod();
    }

    /**
     * Create an instance of {@link SignedInfoType.SignatureMethod }
     * 
     */
    public SignedInfoType.SignatureMethod createSignedInfoTypeSignatureMethod() {
        return new SignedInfoType.SignatureMethod();
    }

    /**
     * Create an instance of {@link ReferenceType.DigestMethod }
     * 
     */
    public ReferenceType.DigestMethod createReferenceTypeDigestMethod() {
        return new ReferenceType.DigestMethod();
    }

    /**
     * Create an instance of {@link Reinf.EvtTotalContrib.IdeEvento }
     * 
     */
    public Reinf.EvtTotalContrib.IdeEvento createReinfEvtTotalContribIdeEvento() {
        return new Reinf.EvtTotalContrib.IdeEvento();
    }

    /**
     * Create an instance of {@link Reinf.EvtTotalContrib.IdeContri }
     * 
     */
    public Reinf.EvtTotalContrib.IdeContri createReinfEvtTotalContribIdeContri() {
        return new Reinf.EvtTotalContrib.IdeContri();
    }

    /**
     * Create an instance of {@link Reinf.EvtTotalContrib.IdeRecRetorno }
     * 
     */
    public Reinf.EvtTotalContrib.IdeRecRetorno createReinfEvtTotalContribIdeRecRetorno() {
        return new Reinf.EvtTotalContrib.IdeRecRetorno();
    }

    /**
     * Create an instance of {@link Reinf.EvtTotalContrib.InfoTotalContrib.RPrest }
     * 
     */
    public Reinf.EvtTotalContrib.InfoTotalContrib.RPrest createReinfEvtTotalContribInfoTotalContribRPrest() {
        return new Reinf.EvtTotalContrib.InfoTotalContrib.RPrest();
    }

    /**
     * Create an instance of {@link Reinf.EvtTotalContrib.InfoTotalContrib.RRecRepAD }
     * 
     */
    public Reinf.EvtTotalContrib.InfoTotalContrib.RRecRepAD createReinfEvtTotalContribInfoTotalContribRRecRepAD() {
        return new Reinf.EvtTotalContrib.InfoTotalContrib.RRecRepAD();
    }

    /**
     * Create an instance of {@link Reinf.EvtTotalContrib.InfoTotalContrib.RComl }
     * 
     */
    public Reinf.EvtTotalContrib.InfoTotalContrib.RComl createReinfEvtTotalContribInfoTotalContribRComl() {
        return new Reinf.EvtTotalContrib.InfoTotalContrib.RComl();
    }

    /**
     * Create an instance of {@link Reinf.EvtTotalContrib.InfoTotalContrib.RCPRB }
     * 
     */
    public Reinf.EvtTotalContrib.InfoTotalContrib.RCPRB createReinfEvtTotalContribInfoTotalContribRCPRB() {
        return new Reinf.EvtTotalContrib.InfoTotalContrib.RCPRB();
    }

    /**
     * Create an instance of {@link Reinf.EvtTotalContrib.InfoTotalContrib.RTom.InfoCRTom }
     * 
     */
    public Reinf.EvtTotalContrib.InfoTotalContrib.RTom.InfoCRTom createReinfEvtTotalContribInfoTotalContribRTomInfoCRTom() {
        return new Reinf.EvtTotalContrib.InfoTotalContrib.RTom.InfoCRTom();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Signature")
    public JAXBElement<SignatureType> createSignature(SignatureType value) {
        return new JAXBElement<SignatureType>(_Signature_QNAME, SignatureType.class, null, value);
    }

}
