//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.04 at 01:57:49 PM BRT 
//


package reinf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Informações de processamento dos eventos
 * 
 * <p>Java class for TDadosProcessamentoEvento complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TDadosProcessamentoEvento">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nrProtEntr">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="49"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dhProcess" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="tpEv">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="idEv">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="36"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="hash">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDadosProcessamentoEvento", namespace = "http://www.reinf.esocial.gov.br/schemas/evtTotalContrib/v1_03_02", propOrder = {
    "nrProtEntr",
    "dhProcess",
    "tpEv",
    "idEv",
    "hash"
})
public class TDadosProcessamentoEvento {

    @XmlElement(required = true)
    protected String nrProtEntr;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dhProcess;
    @XmlElement(required = true)
    protected String tpEv;
    @XmlElement(required = true)
    protected String idEv;
    @XmlElement(required = true)
    protected String hash;

    /**
     * Gets the value of the nrProtEntr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrProtEntr() {
        return nrProtEntr;
    }

    /**
     * Sets the value of the nrProtEntr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrProtEntr(String value) {
        this.nrProtEntr = value;
    }

    /**
     * Gets the value of the dhProcess property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDhProcess() {
        return dhProcess;
    }

    /**
     * Sets the value of the dhProcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDhProcess(XMLGregorianCalendar value) {
        this.dhProcess = value;
    }

    /**
     * Gets the value of the tpEv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTpEv() {
        return tpEv;
    }

    /**
     * Sets the value of the tpEv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTpEv(String value) {
        this.tpEv = value;
    }

    /**
     * Gets the value of the idEv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdEv() {
        return idEv;
    }

    /**
     * Sets the value of the idEv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdEv(String value) {
        this.idEv = value;
    }

    /**
     * Gets the value of the hash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHash() {
        return hash;
    }

    /**
     * Sets the value of the hash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHash(String value) {
        this.hash = value;
    }

}
