//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.04 at 01:57:49 PM BRT 
//


package reinf;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Define uma ocorrencia encontrada no processamento de um arquivo.
 * 
 * <p>Java class for TRegistroOcorrencias complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TRegistroOcorrencias">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tpOcorr">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="localErroAviso">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codResp">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dscResp">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRegistroOcorrencias", namespace = "http://www.reinf.esocial.gov.br/schemas/evtTotalContrib/v1_03_02", propOrder = {
    "tpOcorr",
    "localErroAviso",
    "codResp",
    "dscResp"
})
public class TRegistroOcorrencias {

    @XmlElement(required = true)
    protected BigInteger tpOcorr;
    @XmlElement(required = true)
    protected String localErroAviso;
    @XmlElement(required = true)
    protected String codResp;
    @XmlElement(required = true)
    protected String dscResp;

    /**
     * Gets the value of the tpOcorr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTpOcorr() {
        return tpOcorr;
    }

    /**
     * Sets the value of the tpOcorr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTpOcorr(BigInteger value) {
        this.tpOcorr = value;
    }

    /**
     * Gets the value of the localErroAviso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalErroAviso() {
        return localErroAviso;
    }

    /**
     * Sets the value of the localErroAviso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalErroAviso(String value) {
        this.localErroAviso = value;
    }

    /**
     * Gets the value of the codResp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodResp() {
        return codResp;
    }

    /**
     * Sets the value of the codResp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodResp(String value) {
        this.codResp = value;
    }

    /**
     * Gets the value of the dscResp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDscResp() {
        return dscResp;
    }

    /**
     * Sets the value of the dscResp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDscResp(String value) {
        this.dscResp = value;
    }

}
